trigger:
- main
- release
- develop

pool:
  name: 'Energy Build'

steps:
- task: AWSCLI@1
  displayName: 'Upload Glue Script to S3'
  inputs:
    awsCredentials: 'new_service_connection'
    regionName: 'us-east-1'
    command: 's3 cp'
    arguments: '$(Build.ArtifactStagingDirectory)/co_energy_market_curado_providers.py s3://co-energy-marketer-artifacts-569587453819-pdn/scripts/co_energy_market_curado_providers.py'
