"""Constants"""

DOMAIN: str ="marketer"
CAPACITY: str ="energy"
PAIS: str ="co"
CATALOG_TABLE_NAME_PROVIDERS: str ="Providers"
CURATED_TABLE_NAME_PROVIDERS: str="energy_providers"
DATA_PRODUCT_PROVIDERS: str = "table_energy_providers"
NAME_PROVIDERS: str = "nombre_proveedor"
CATALOG_TABLE_NAME_CUSTOMERS: str ="Customers"
CURATED_TABLE_NAME_CUSTOMERS: str="energy_customers"
DATA_PRODUCT_CUSTOMERS: str = "table_energy_customers"
NAME_CUSTOMERS: str = "nombre"
CATALOG_TABLE_NAME_TRANSACTIONS: str ="Transactions"
CURATED_TABLE_NAME_TRANSACTIONS: str="energy_transactions"
DATA_PRODUCT_TRANSACTIONS: str = "table_energy_transactions"
NAME: str = "nombre"
PRECIO: str = "precio"
